volumes:
  digidaro-vol:

services:

  pg_database:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - digidaro-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432 
  python:
    build:
      context: .
      dockerfile: ./docker/python.Dockerfile
    depends_on:
      - pg_database
    # uses port 80 for direct access to localhost
    ports:
      - 80:5000
    # the Flask application will go into the 'server' folder of the project and mapped to '/usr/src/app' in the container
    volumes:
      - ./app:/user/src/app
    